name: Generate Coverage Badge

on:
  push:
    branches:
      - main
    paths-ignore:
      - "coverage-badge.svg"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Allow pushing
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run coverage and generate badge
        run: npm run coverage:ci

      - name: Commit coverage badge
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage-badge.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'chore: update coverage badge'
            git push origin HEAD:${{ github.ref }}
          fi
